"""Executable coverage manifest: every registered capability has a chat request."""
from dataclasses import dataclass, field

@dataclass
class Case:
    name: str
    question: str
    arguments: dict = field(default_factory=dict)

CASES = [
Case("get_money_overview","Show my overall financial picture"),
Case("get_paycheck_plan","Show my paycheck allocation plan for September 2026",{"year":2026,"month":9}),
Case("get_spending_allowance","How much can I safely spend in the next 14 days?",{"days":14}),
Case("get_cash_forecast","Forecast cash in Everyday Checking for 30 days",{"account_id":"acc_checking","days":30}),
Case("get_upcoming_obligations","What bills are due in the next 30 days?",{"days":30}),
Case("compare_debt_strategies","Compare debt payoff strategies with 300 extra monthly",{"extra_payment":300}),
Case("what_if_extra_payment","What if I pay 300 extra toward debt?",{"amount":300}),
Case("get_mortgage_scenarios","Compare mortgage scenarios with a 1000 lump sum and 100 extra monthly",{"lump_sum":1000,"extra_monthly":100}),
Case("compare_biweekly_mortgage","Compare biweekly mortgage payments with an annual program fee of 50",{"program_fee_per_year":50}),
Case("plan_promotional_payoff","Plan promotional payoff of 1200 across 6 remaining paychecks",{"balance":1200,"paychecks_remaining":6}),
Case("choose_card","Choose a card for 80 dollars of dining",{"amount":80,"category":"dining"}),
Case("compare_card_vs_bank_for_bill","Compare card vs bank payment for a 500 bill with 2 percent card rewards and 3 percent processing fee",{"amount":500,"card_rate":0.02,"processing_fee_rate":0.03}),
Case("compare_booking_channels","Compare a 500 direct booking with a 480 portal booking",{"direct_price":500,"portal_price":480}),
Case("check_utilization_timing","Check utilization timing for Everyday Rewards with a 200 payment",{"card_id":"card_a","payment":200}),
Case("get_buffer","Show my checking buffer",{"account_id":"acc_checking"}),
Case("assess_sweep_move","Assess a hypothetical 1000 sweep held 30 days at 4 percent APY with no fee",{"amount":1000,"hold_days":30,"destination_apy":0.04,"transfer_fee":0}),
Case("get_liquidity_tiers","Show liquidity tiers"),
Case("compare_payment_timing","Compare timing for a 500 payment due 2026-09-30",{"amount":500,"due_date":"2026-09-30"}),
Case("get_tax_profile","Show my tax assumptions"),
Case("compare_savings_vs_debt","Compare putting 1000 into savings versus debt for 365 days",{"amount":1000,"horizon_days":365}),
Case("check_interest_deduction","Explain mortgage interest deduction eligibility",{"loan_type":"mortgage"}),
Case("get_deposit_coverage","Show my deposit insurance coverage"),
Case("plan_coverage_remedy","Plan a coverage remedy for First Meridian Bank",{"source_institution":"bank_meridian"}),
Case("stress_collateral_line","Stress collateral worth 100000 at an advance rate of 0.5 with 20000 drawn",{"collateral_value":100000,"advance_rate":0.5,"drawn":20000}),
Case("get_automation_status","Show automation status"),
Case("get_account_connections","Show account connection health"),
Case("get_recurring_activity","Show recurring activity for the next 45 days",{"horizon_days":45}),
Case("explain_transfer_outcome","Explain the latest simulated transfer outcome"),
Case("stress_income_loss","What if I lose 2 months of income?",{"months":2}),
Case("explain_product_boundary","Explain product limitations for investment trading",{"topic":"investment trading"}),
Case("create_account","Create a manual checking account called Travel Cash with a current balance of 100",{"nickname":"Travel Cash","type":"checking","current":"100"}),
Case("update_account","Change Everyday Checking nickname to Daily Cash",{"record_id":"acc_checking","nickname":"Daily Cash"}),
Case("create_income","Create a monthly income source called Bonus, net amount 250, deposited into Everyday Checking, starting 2026-10-01",{"record_type":"source","name":"Bonus","net_amount":"250","deposit_account_id":"acc_checking","next_date":"2026-10-01","cadence":"monthly"}),
Case("update_income","Change Salary (semi-monthly) net amount to 3100",{"record_id":"inc_salary","net_amount":"3100"}),
Case("create_bill","Create a monthly bill named Music, amount 12.99, due 2026-10-05, funded by Everyday Checking",{"name":"Music","amount":"12.99","due_date":"2026-10-05","funding_account_id":"acc_checking","cadence":"monthly"}),
Case("update_bill","Change Mortgage payment bill amount to 1999.99",{"record_id":"bill_mortgage","amount":"1999.99"}),
Case("create_goal","Create a savings goal named Holiday, in Emergency & Annual Savings, target 1000",{"name":"Holiday","account_id":"acc_savings","target":"1000"}),
Case("update_goal","Change Emergency reserve goal target to 16000",{"record_id":"res_emergency","target":"16000"}),
Case("create_rule","Create rule Travel savings, purpose goal, fixed amount 50, from Everyday Checking to Emergency & Annual Savings, on each income",{"name":"Travel savings","purpose":"goal","method":"fixed","amount":"50","source_account_id":"acc_checking","destination_account_id":"acc_savings","cadence":"on_income"}),
Case("update_rule","Rename Mortgage required payment rule to Home allocation",{"record_id":"pol_mortgage","name":"Home allocation"}),
Case("update_tax","Set federal marginal tax rate to 25 percent",{"federal_marginal":"0.25"}),
Case("pause_rule","Pause Mortgage required payment rule",{"record_id":"pol_mortgage"}),
Case("resume_rule","Resume Mortgage required payment rule",{"record_id":"pol_mortgage"}),
Case("skip_rule","Skip the next Mortgage required payment rule occurrence",{"record_id":"pol_mortgage"}),
Case("authorize_rule","Authorize Mortgage required payment rule for simulation with a per-run cap of 2000",{"record_id":"pol_mortgage","per_run_cap":"2000"}),
Case("draft_bill_payment","Prepare a one-time Mortgage payment bill draft",{"record_id":"bill_mortgage"}),
Case("build_payment_drafts","Build payment drafts for September 2026",{"year":2026,"month":9}),
Case("simulate_payment","Run the sample payment group {group}",{"record_id":"$group"}),
Case("recover_payment","Recover the sample payment leg {leg}",{"record_id":"$leg"}),
Case("pause_execution","Pause all execution"),
Case("resume_execution","Resume all execution"),
Case("correct_transaction","Correct transaction {transaction} category to subscriptions",{"record_id":"$transaction","category":"subscriptions"}),
Case("import_transactions","Import the uploaded CSV attachment {attachment}",{"attachment_id":"$attachment"}),
Case("upload_csv","Open the CSV upload form for Everyday Checking",{"account_id":"acc_checking"}),
Case("list_records","List my bill records",{"kind":"bill"}),
Case("search_transactions","Find my transactions matching Music",{"query":"Music"}),
Case("list_audit","Show recent workspace changes"),
Case("list_payment_groups","Show payment groups"),
Case("list_documents","List my documents"),
Case("search_documents","Search my documents for annual fee",{"query":"annual fee"}),
Case("read_document","Open the document Annual report",{"record_id":"$document"}),
Case("list_conversations","List saved conversations"),
Case("list_connections","List my connections"),
Case("browse_mcp","Browse approved tools for Report source",{"record_id":"$mcp"}),
Case("delete_document","Delete document Annual report",{"record_id":"$document"}),
Case("delete_conversation","Delete conversation Old conversation",{"record_id":"$conversation"}),
Case("disconnect_mcp","Disconnect Report source",{"record_id":"$mcp"}),
Case("revoke_mcp_access","Revoke MCP access named Test access",{"record_id":"$grant"}),
Case("sync_bank","Sync Fixture Bank connection",{"record_id":"$bank"}),
Case("disconnect_bank","Disconnect Fixture Bank connection",{"record_id":"$bank"}),
Case("import_mcp","Import approved statement tool from Report source as a document",{"record_id":"$mcp","tool_name":"statement"}),
Case("connect_bank","Connect my bank"),
Case("connect_mcp","Connect an MCP source"),
Case("create_mcp_access","Create MCP access"),
Case("upload_document","Upload a document"),
Case("select_documents","Open document selection"),
Case("new_conversation","Start a new conversation"),
Case("open_conversation","Open conversation Old conversation",{"record_id":"$conversation"}),
Case("navigate","Open the goals page",{"page":"goals"}),
Case("explain_capabilities","What can you do?"),
]