/** Execution UI contracts: deliberate consent, exact API scopes, current status and sample-only simulation. */
import assert from 'node:assert/strict';
import { S } from '../finpilot/web/core.js';
import { initializeExecution, handleExecutionClick, handleExecutionSubmit } from '../finpilot/web/execution.js';
let html = '', errors = [], requests = [], loads = 0;
const body = {get innerHTML(){return html}, set innerHTML(value){html=value}};
const dialog = {open:false,showModal(){this.open=true},close(){this.open=false},querySelector(){return null}};
globalThis.document = {getElementById(id){return {'detail-body':body,'detail-dialog':dialog,'assistant-dialog':{open:false}}[id] || null}};
globalThis.FormData = class {constructor(form){this.values=new Map(Object.entries(form.values))} has(k){return this.values.has(k)} get(k){return this.values.get(k)}};
S.session = {user:{id:'user-a'},csrf_token:'test-csrf'};
S.revision=3;
S.workspace={household:{base_currency:'USD',payment_sandbox:true},accounts:[{id:'checking',nickname:'Daily & spending'},{id:'savings',nickname:'Savings'}],policies:[{id:'rule-a',name:'Save monthly',source_account_id:'checking',destination_account_id:'savings',purpose:'goal',amount:{amount:'1234.56'},mandate:{}}],bills:[],income_events:[{id:'pay-a',expected_date:'2026-09-11'}]};
let state='draft',blocked=false,paused=false;
const group = () => ({group_id:'group-a',label:'Paycheck 2026-09-11',legs:1,detail:[{id:'leg-a',group_id:'group-a',source_account_id:'checking',destination:'savings',policy_id:'rule-a',amount:{amount:'1234.56',currency:'USD'},fee:{amount:'0',currency:'USD'},scheduled_for:'2026-09-11',kind:'reserve_funding',optional:true,state}]});
const response = value => ({ok:true,status:200,headers:{get(){return '4'}},async json(){return value}});
globalThis.fetch = async (url, options={}) => {
  requests.push({url,options,body: options.body ? JSON.parse(options.body) : null});
  if(url.startsWith('/api/execution/groups/')) return response({group:group(),preflight:{'leg-a':{ok:!blocked,checks:{funding:!blocked},blockers:blocked?['Not enough available funds']:[]}},globally_paused:paused,provider:'simulation'});
  if(url.startsWith('/api/execution/build?')) return response({groups:[group()]});
  if(url.endsWith('/authorize')) return response({mode:'one_time',per_run_cap:{amount:'1234.56',currency:'USD'},note:'Sample authority saved.'});
  if(url.startsWith('/api/execution/run/')) {state='reconciled';return response({group:'group-a',results:[{state}]})}
  if(url.startsWith('/api/execution/recover/')) return response({leg:group().detail[0],action:'Original payment checked. No replacement submitted.'});
  if(url.endsWith('/pause-all')) {paused=true;return response({note:'Future runs paused',canceled:['leg-a'],already_sent_cannot_be_stopped:[]})}
  if(url.endsWith('/resume')) {paused=false;return response({note:'Future eligible runs resumed',globally_paused:false})}
  throw new Error('Unexpected API: '+url);
};
initializeExecution({load:async()=>loads++,toast:(m)=>errors.push(m)});
const click = target => handleExecutionClick({dataset:{execution:target}});
const makeForm=(kind,values={},id='rule-a')=>{const status={textContent:''},button={disabled:false};return {dataset:{executionForm:kind,id},values,status,button,reportValidity(){return true},querySelector(selector){return selector==='.form-result'?status:button}}};
await click('authorize:rule-a');
assert.ok(html.includes('One simulated payment'));
assert.ok(html.includes('value="1234.56"'));
assert.ok(html.includes('Daily &amp; spending'));
assert.equal(requests.length,0,'Opening consent is read-only');
const noConsent=makeForm('authorize',{mode:'one_time',per_run_cap:'1234.56'});
await handleExecutionSubmit(noConsent);
assert.equal(requests.length,0,'Consent is required before authorization');
assert.match(noConsent.status.textContent,/confirmation/);
await handleExecutionSubmit(makeForm('authorize',{confirmed:'on',mode:'one_time',per_run_cap:'1234.56'}));
assert.deepEqual(requests[0].body,{mode:'one_time',per_run_cap:'1234.56'});
assert.equal(requests[0].options.headers['X-CSRF-Token'],'test-csrf');
await click('build:pay-a');
const build=requests.find(r=>r.url.startsWith('/api/execution/build'));
assert.ok(build.url.includes('income_event_id=pay-a'));
assert.ok(build.url.includes('year=2026')&&build.url.includes('month=9'));
assert.ok(html.includes('Run payment simulation'));
assert.ok(html.includes('fictional balances'));
assert.equal(requests.filter(r=>r.url.startsWith('/api/execution/run')).length,0,'Draft build and review never run payments');
blocked=true;await click('group:group-a');
assert.ok(html.includes('Not enough available funds'));
assert.match(html,/type="submit" class="button primary" disabled>Run payment simulation/);
blocked=false;await click('group:group-a');
await handleExecutionSubmit(makeForm('simulate',{confirmed:'on'},'group-a'));
assert.deepEqual(requests.find(r=>r.url.startsWith('/api/execution/run')).body,{confirm_simulation:true});
assert.ok(html.includes('Reconciled'));
assert.ok(!html.includes('Run payment simulation'),'Completed group cannot be run again');
state='outcome_unknown';await click('group:group-a');
assert.ok(html.includes('Check original payment status'));
await click('recover:leg-a:group-a');
assert.equal(requests.filter(r=>r.url.startsWith('/api/execution/run')).length,1,'Recovery does not create a replacement');
assert.ok(html.includes('Original payment checked'));
await click('pause');await handleExecutionSubmit(makeForm('pause',{confirmed:'on'},''));
assert.ok(html.includes('Execution paused'));
await click('resume');await handleExecutionSubmit(makeForm('resume',{confirmed:'on'},''));
assert.ok(html.includes('Future simulation resumed'));
S.workspace.household.payment_sandbox=false;state='draft';
await click('group:group-a');
assert.ok(html.includes('Your recorded balances are not changed'));
assert.ok(!html.includes('data-execution-form="simulate"'));
await click('authorize:rule-a');
assert.ok(!html.includes('data-execution-form="authorize"'));
const before=requests.length;
await handleExecutionSubmit(makeForm('simulate',{confirmed:'on'},'group-a'));
assert.equal(requests.length,before,'Real-workspace confirmation cannot call simulator');
assert.ok(loads>=5);
assert.deepEqual(errors,['Simulation authorization saved.']);
console.log('Execution UI: authorization consent, exact paycheck draft, blocked checks, confirmed simulation, recovery, global pause/resume and real-workspace isolation pass.');
