"""Generate reference documentation that must never drift from the code.

Usage (needs the application's dependencies, for example .venv/Scripts/python.exe):
    python scripts/build_docs.py           # write the generated references
    python scripts/build_docs.py --check   # exit 1 when a generated reference is out of date

Generated files:
    docs/api/openapi.json    OpenAPI schema of every HTTP route, described by finpilot/api/route_docs.py
    docs/api-reference.md    Readable API reference built from that schema
    docs/ai-capabilities.md  Every assistant capability, from finpilot/ai/capabilities.py
    docs/data-model.md       Every database table, from the SQLAlchemy models, plus the household snapshot
"""

from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

HEADER = "<!-- Generated by scripts/build_docs.py. Do not edit by hand; run the script instead. -->\n"


def _cell(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def openapi_schema() -> dict:
    from finpilot.api.app import create_app
    return create_app("sqlite://").openapi()


def _schema_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " or ".join(_schema_type(option) for option in schema["anyOf"])
    if schema.get("type") == "array":
        return f"array of {_schema_type(schema.get('items', {}))}"
    return schema.get("type", "value")


def api_reference(schema: dict) -> str:
    lines = [HEADER, "# API reference", "",
             f"{schema['info']['title']} API {schema['info']['version']}. A running server also serves this reference "
             "interactively at `/docs` and `/redoc`, and the machine-readable schema is `docs/api/openapi.json`.", "",
             "**Authentication.** Sign in with `POST /api/auth/login`; the session cookie then authenticates requests. "
             "Every write must also send the `X-CSRF-Token` value from `GET /api/auth/me`. Workspace writes accept "
             "`If-Match` with the current workspace revision and fail with `409` when it has changed. The MCP export "
             "endpoints use a FinPilot MCP bearer token instead of the cookie.", ""]
    groups: dict[str, list] = {}
    for path, operations in schema["paths"].items():
        for method, operation in operations.items():
            groups.setdefault((operation.get("tags") or ["Service"])[0], []).append((path, method.upper(), operation))
    lines += ["## Contents", ""] + [f"- {tag} ({len(ops)})" for tag, ops in groups.items()] + [""]
    for tag, operations in groups.items():
        lines += [f"## {tag}", ""]
        for path, method, operation in operations:
            lines += [f"### {operation.get('summary', path)}", "", f"`{method} {path}`", "",
                      operation.get("description", ""), ""]
            parameters = operation.get("parameters", [])
            if parameters:
                lines += ["| Parameter | In | Required | Type |", "| --- | --- | --- | --- |"]
                lines += [f"| `{p['name']}` | {p['in']} | {'yes' if p.get('required') else 'no'} | "
                          f"{_cell(_schema_type(p.get('schema', {})))} |" for p in parameters]
                lines.append("")
            content = operation.get("requestBody", {}).get("content", {})
            if content:
                bodies = [f"`{kind}` ({_schema_type(body.get('schema', {}))})" for kind, body in content.items()]
                lines += ["Request body: " + ", ".join(bodies) + ".", ""]
            errors = [(code, info) for code, info in operation.get("responses", {}).items() if code[:1] in "45"]
            if errors:
                lines += ["| Error | Meaning |", "| --- | --- |"]
                lines += [f"| `{code}` | {_cell(info.get('description', ''))} |" for code, info in errors]
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


MODES = [
    ("read", "Read and calculate", "Answers from current workspace data. Nothing changes."),
    ("write", "Change workspace records", "Returns a preview. Nothing changes until you confirm it."),
    ("private", "Manage your private items", "Deletes or revokes your own documents, conversations and access after confirmation."),
    ("provider", "Call an outside provider", "Runs a bank or MCP operation after confirmation, outside the financial transaction."),
    ("handoff", "Open a secure form", "Opens an application form, for example to upload a file or connect a bank."),
    ("navigate", "Navigate", "Opens an application screen."),
]


def ai_capabilities() -> str:
    from finpilot.ai.capabilities import catalog
    from finpilot.ai.tools import ToolRegistry
    from finpilot.engine.tax import TaxProfile
    from finpilot.execution.engine import ExecutionEngine
    from finpilot.seed.demo import demo_household
    from tests.chat_capability_manifest import CASES

    household = demo_household()
    ctx = SimpleNamespace(household=household,
                          registry=ToolRegistry(household, TaxProfile(), ExecutionEngine(household)))
    capabilities = catalog(ctx)
    examples: dict[str, str] = {}
    for case in CASES:
        examples.setdefault(case.name, case.question)

    lines = [HEADER, "# AI capabilities", "",
             f"The assistant can use {len(capabilities)} capabilities. Financial numbers always come from deterministic "
             "calculations, and every change is previewed and needs explicit confirmation. Example requests come from "
             "`tests/chat_capability_manifest.py`, which exercises every capability.", ""]
    for mode, title, meaning in MODES:
        group = [c for c in capabilities.values() if c.mode == mode]
        if not group:
            continue
        lines += [f"## {title}", "", meaning, "",
                  "| Capability | What it does | Required inputs | Example request |", "| --- | --- | --- | --- |"]
        for cap in group:
            required = ", ".join(f"`{name}`" for name in cap.schema.get("required", [])) or "none"
            description = cap.description + (" Sample workspaces only." if cap.sample_only else "")
            example = _cell(examples.get(cap.name, "")) or "-"
            lines.append(f"| `{cap.name}` | {_cell(description)} | {required} | {example} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def data_model() -> str:
    from finpilot.models import Household
    from finpilot.persistence.database import Base

    classes = {mapper.local_table.name: mapper.class_ for mapper in Base.registry.mappers}
    tables = sorted(Base.metadata.tables.values(), key=lambda t: t.name)
    lines = [HEADER, "# Data model", "",
             f"FinPilot stores {len(tables)} tables. Each household's financial records live in one versioned JSON "
             "snapshot in `households.snapshot`; transactions are also written to the `transactions` table for indexed "
             "history. Alembic migrations in `alembic/versions/` own the hosted schema. See `ARCHITECTURE.md` for the "
             "consistency and tenant rules.", "", "## Tables", ""]
    lines += [f"- `{t.name}` ({classes[t.name].__module__}.{classes[t.name].__name__})" if t.name in classes
              else f"- `{t.name}`" for t in tables]
    lines.append("")
    for table in tables:
        lines += [f"### {table.name}", "", "| Column | Type | Nullable | Keys |", "| --- | --- | --- | --- |"]
        for column in table.columns:
            keys = []
            if column.primary_key:
                keys.append("primary key")
            keys += [f"references `{fk.target_fullname}`" for fk in sorted(column.foreign_keys, key=lambda f: f.target_fullname)]
            if column.unique:
                keys.append("unique")
            if column.index:
                keys.append("indexed")
            lines.append(f"| `{column.name}` | {_cell(repr(column.type))} | {'yes' if column.nullable else 'no'} | "
                         f"{', '.join(keys) or '-'} |")
        lines.append("")
    lines += ["## Household snapshot", "",
              "Top-level fields of `finpilot.models.Household`, the aggregate stored in `households.snapshot`.", "",
              "| Field | Type |", "| --- | --- |"]
    lines += [f"| `{field.name}` | {_cell(field.type if isinstance(field.type, str) else getattr(field.type, '__name__', field.type))} |"
              for field in dataclasses.fields(Household)]
    return "\n".join(lines).rstrip() + "\n"


def render_all() -> dict[Path, str]:
    schema = openapi_schema()
    return {
        ROOT / "docs" / "api" / "openapi.json": json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
        ROOT / "docs" / "api-reference.md": api_reference(schema),
        ROOT / "docs" / "ai-capabilities.md": ai_capabilities(),
        ROOT / "docs" / "data-model.md": data_model(),
    }


def check() -> list[str]:
    stale = []
    for path, text in render_all().items():
        current = path.read_bytes().decode("utf-8").replace("\r\n", "\n") if path.exists() else None
        if current != text:
            stale.append(path.relative_to(ROOT).as_posix())
    return stale


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if "--check" in args:
        stale = check()
        if stale:
            print("build_docs: out of date: " + ", ".join(stale))
            print("Run: python scripts/build_docs.py")
            return 1
        print("build_docs: generated references are current")
        return 0
    for path, text in render_all().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode("utf-8"))
        print(f"wrote {path.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
